# Generated by Django 4.2.5 on 2023-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idAlumno', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('fecha_nac', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='idProducto',
            new_name='idAlumno',
        ),
    ]
