FROM python:3.11-alpine

ENV PYTHONUNBUFFERED=1

WORKDIR /app5

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 9000

CMD ["python","manage.py","runserver","0.0.0.0:9000"]

